### ISSUE TITLE
这里可以补充一句

### ISSUE THREAD

**Issue by hellohejinyu** [duan602728596/duan602728596.github.io#1]
https://github.com/duan602728596/duan602728596.github.io/blob/1d509e2cc7d0c454e165cbb9dbdd443e04000b7c/src/pages/Article/DomToImage/Article.js#L35

Chrome 下可以把包含样式的 `style` 标签内容一并加进去，然后就可以通过类名来设置样式了。

**Comment by duan602728596** [comment]
奥，懂了。那之前加不进去的应该是因为样式表的问题
